### ISSUE TITLE
[Feature] Player's Run State

### ISSUE THREAD

**Issue by rluders** [CodeCafeOpenShiftGame/PodEscape#11]
We need to implement the Player's move state to be used in our StateMachine. It is already partially implemented, but need to be changed, tested and polished. Right now the player needs to use the `A` and `D` key to move, backward and forwards.

**Describe the solution you'd like**
- The user doesn't need to hold key to the character runs;
- The character will be always moving forward (to the right);

**Additional context**
It's important to identify the state transitions to this state.

**Comment by RoddieKieley** [comment]
Taking a look I see that there was an update in the air-state branch via commit [d4dc1e05f5571e6659eb14e5eb6f6a413da55fad](https://github.com/CodeCafeOpenShiftGame/PodEscape/commit/d4dc1e05f5571e6659eb14e5eb6f6a413da55fad) that enabled auto-running but he immediately auto-runs off the limit. Going to create a branch for endless running, #3, and test from there.

**Comment by RoddieKieley** [comment]
Endless running was implemented shortly after the above comment but just now closing the loop.
