### ISSUE TITLE
[Feature] Player's Dash State

### ISSUE THREAD

**Issue by rluders** [CodeCafeOpenShiftGame/PodEscape#12]
The player must be able to increase its speed for a moment. It can be done using the dash movement, while in the air. It should not affect the player's vertical speed.

**Describe the solution you'd like**
- The player can only use the dash while in the air;
- The player speed increases for a moment (not the camera movement);

**Describe alternatives you've considered**
- Maybe the dash movement can also be used while in groud?

**Comment by rluders** [comment]
Interesting tutorial to create the Ghost effect that can be added to the Dash movement.
https://www.youtube.com/watch?v=_8AzOdLuUyA

**Comment by ergonzal22** [comment]
Dash state finished
