### ISSUE TITLE
[Feature] Configure autotiling in the editor using test tilemap

### ISSUE THREAD

**Issue by RoddieKieley** [CodeCafeOpenShiftGame/PodEscape#2]
Within the GoDot editor one of the features added recently was autotiling. This allows you to configure a texture atlas such that you can use it as a brush to draw your levels in a very user friendly way as shown [here](https://youtu.be/uV5WKocIycY?list=PL9FzW-m48fn2jlBu_0DRh7PvAt-GULEmd&t=435)

**Comment by rluders** [comment]
Small tutorial from GDQuest can be found [here](https://www.youtube.com/watch?v=V9OoaOlXc_4).

**Comment by rluders** [comment]
I was trying to do something else today, but... I'm just too tired. I tried to do some tests with the autotiling, but, no success. Not sure if the autotiling will be nice to us, it will depend pretty much on the art that we will have to design the maps. So fat, looking to the mockups, I don't feel like it looks like tilemap levels.

How about this?
https://www.youtube.com/watch?v=WFu1utKAZ18

**Comment by rluders** [comment]
I guess that we drop this one, right?
