### ISSUE TITLE
Figure out HTML5 and WebAssembly delivery via OpenShift + Document it

### ISSUE THREAD

**Issue by dudash** [CodeCafeOpenShiftGame/PodEscape#21]
Figure out and Document how to release HTML5 and build/deliver Webassembly from OpenShift

**Comment by dudash** [comment]
https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_web.html

**Comment by RoddieKieley** [comment]
The http-ex example that comes out of the box is a good start, there's a custom one [here](https://github.com/RoddieKieley/httpd-ex) that allows you to deploy the generated html5 output from Godot, once configured as an export target, to OpenShift via S2I.

**Comment by dudash** [comment]
found this in the docs too:
https://docs.godotengine.org/en/3.2/getting_started/workflow/export/exporting_for_web.html

and more generally:
https://docs.godotengine.org/en/3.2/getting_started/step_by_step/exporting.html

with the note:
```While WASM is supported in all major browsers, it is still an emerging technology and you may find some things that don’t work. Make sure you have updated your browser to the most recent version, and report any bugs you find at the Godot Github repository.```

**Comment by RoddieKieley** [comment]
See the recent wiki addition relatated to [Building-PodEscape](https://github.com/CodeCafeOpenShiftGame/PodEscape/wiki/Building-PodEscape) for details.
