### ISSUE TITLE
[Feature] Implement Endless Running using random scenes

### ISSUE THREAD

**Issue by RoddieKieley** [CodeCafeOpenShiftGame/PodEscape#3]
As per the director's pitch doc, as a first step to having an endless runner that has actual content we need a player character that runs automatically from left to right with tiles that are automatically created as they are oncoming and destroyed as they are past and thus are off-screen to the left of the character.

**Comment by rluders** [comment]
I would like to discuss this implementation before it gets implemented. In fact, I think that maybe the title could lead to some misunderstood.

In my understand what we are randomizing is not the "tileset", but some prefabricated scenes, that will contain the level puzzles.

**Comment by rluders** [comment]
The idea is that we should have the `Scenes/World.tscn` that will have a `LevelController` that is responsible for spawn new `scenes` from a `SceneList` object.

The same controller should also remove the `scenes` after it leaves the visible area.

**Comment by RoddieKieley** [comment]
Agreed, this was little misleading in that we are using a building block approach. Going to take a look at this as a part of the run state evaluation, #11, as if there's no where to run it's hard to judge how well it works.

**Comment by rluders** [comment]
@RoddieKieley check this out

https://github.com/CodeCafeOpenShiftGame/PodEscape/tree/level-spawn

I  was just doing some experiments. Of course, it need to be improved, but... you know, that's a start;

**Comment by RoddieKieley** [comment]
Cherry-picked the [level-spawn](https://github.com/CodeCafeOpenShiftGame/PodEscape/tree/level-spawn) code from @rluders and added a little work on the camera, floor scenes and default movement to the right via a "local" [issue3](https://github.com/RoddieKieley/PodEscape/tree/issue3) branch which is now rebased into master via commit [4440b720f116f9842d6b6c706e953f4167da9dca](https://github.com/CodeCafeOpenShiftGame/PodEscape/commit/4440b720f116f9842d6b6c706e953f4167da9dca)
