### ISSUE TITLE
Implement "Go Fast" controls

### ISSUE THREAD

**Issue by RoddieKieley** [CodeCafeOpenShiftGame/PodEscape#4]
Once we have Endless Running, #3, we can begin to implement actions for our player character ADA. ADA needs to be able to "Go Fast" through both sliding and dashing mechanisms. This issue needs updated input handling as well as either test or rough animations for each of slide and dash.

**Comment by rluders** [comment]
The StateMachine is implemented and I'm splitting the Player State into small issues.
If you are OK with that @RoddieKieley, this issue can be closed in favor of these small task implementations. Unless I'm missing something here.
