### ISSUE TITLE
[Feature] Creates the GameManager

### ISSUE THREAD

**Issue by rluders** [CodeCafeOpenShiftGame/PodEscape#7]
We need to create the GameManager class.

This class should be the responsible to manage the game state and the game parameters (like level, speed, points, etc). It probably should be autoloaded/singleton class that can be access from all the game scenes and keep its state.

**Comment by dudash** [comment]
I think this is done as of PR #20

**Comment by ergonzal22** [comment]
Done. For further improvement, we can open a new issue
